apiVersion: v1
kind: ConfigMap
metadata:
  name: urls-configmap
data:
  urls.txt: |
    https://example.com
    https://microsoft.com/
    https://dsjkdjs-dsdsjds-dshjdhsjsd/foo
    http://www.google.com/this/doesnt/exist
